Setup

In [1]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [2]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
# print(arr_1d)


In [3]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10, 10)
# print(arr_2d)


In [4]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match
arr_3d = np.arange(4*5*3).reshape(4,5,3)
# print(arr_3d)
arr_3d.shape


(4, 5, 3)

**Explain:**
- What does `.shape` represent?
  - In NumPy, .shape tells you the dimensions of an array — that is, how many elements it has along each axis.
- Why does contiguous memory matter?
  - It matters because it allows for faster CPU access (cache friendly).


Section 1.2 — dtype & Memory

In [6]:
# TODO:
# Create two arrays with same values but different dtypes

arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
arr_float = np.array([1, 2, 3, 4], dtype=np.float32)
print(arr_int.dtype, arr_float.dtype)


int32 float32


In [8]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print(arr_int.nbytes, arr_float.nbytes)


16 16


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?
  - In big ML pipelines it matters because:
	- Memory: smaller dtypes use less RAM, so you can fit bigger datasets/batches/models.
	- Speed: smaller/optimized dtypes often run faster on GPUs.
	- Accuracy: too-small precision can make numbers “less exact” and hurt training.


Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [11]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(16).reshape(4, 4)
A_slice = A[::2, :]
print(A)
print(A_slice)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [21]:
# TODO:
# Modify A_slice and observe A
A = np.arange(16).reshape(4, 4)
# A_slice = A[::2, :].copy()
A_slice = A[::2, :]
A_slice[:] = -1

A_slice2 = A[::2, :].copy()
A_slice2[:] = -1

print(A)
print(A_slice2)



[[-1 -1 -1 -1]
 [ 4  5  6  7]
 [-1 -1 -1 -1]
 [12 13 14 15]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]]


Explain:
- Why did the original array change (or not)?
  - The original array changed because A_slice is a view made by slicing, so it shares the same memory as A. Modifying A_slice modifies A (for the sliced rows).
  - A_slice2 (the one made with .copy()) is a separate copy of the data, not a view.
	  - A_slice2 = A[::2, :].copy() allocates new memory and duplicates those rows.
	  - If you modify A_slice2, A will not change, because they no longer share memory.


Section 2.2 — Boolean Masking

In [25]:
# TODO:
# Create random array of size 1000

# X = np.random.rand(1000)
X = np.random.randint(0, 500, size=1000)
# print(X)


In [27]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask
m = X.mean()
val_grt_m = X[X>m]
# print(val_grt_m)




In [28]:
# TODO:
# Replace negative values with 0 (no loops)

X[X < 0] = 0

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [31]:
# TODO:
# Create A (1000, 50) and b (50,)

A = np.arange(1000 * 50).reshape(1000, 50)
b = np.arange(50,)


In [34]:
# TODO:
# Add b to each row of A

# HINT:
# - No reshape required
Ab = A+b
# print(AB)

In [37]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind
A_norm = A / A.sum(axis=1, keepdims=True)
# print(A_norm)



Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [ ]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it



What was wrong with the original shapes?


Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [ ]:
# TODO:
# Create large array X of size 1,000,000

X = ...


In [ ]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it




In [ ]:
# TODO:
# Normalize using vectorization



Why is vectorization faster?


Task 4.2: Pairwise Distance (FAANG Classic)

In [ ]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
    ...


Section 5 — Numerical Stability

Task 5.1: Softmax

In [ ]:
# TODO:
# Implement naive softmax

def softmax_naive(X):
    ...


In [ ]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    ...


Why does subtracting max work?


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [ ]:
# TODO:
# Try valid and invalid matrix multiplications



Explain difference between dot, @, and matmul.


Task 6.2: Solving Linear Systems

In [ ]:
# TODO:
# Solve Ax = b and verify solution


Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [ ]:
# TODO:
# Compare in-place vs out-of-place operations




Task 7.2: Strides

In [ ]:
# TODO:
# Inspect array strides and explain



Section 8 — Mini Case Study

In [ ]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors



Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
